In [1]:
import numpy as np

In [7]:
a=np.array([2,3,4])
a

array([2, 3, 4])

In [11]:
a.shape

(3,)

In [13]:
a.ndim

1

In [15]:
a.size

3

In [17]:
a.itemsize

4

In [25]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
b.shape

(2, 3)

In [29]:
b.ndim

2

In [31]:
b.size

6

In [33]:
b.itemsize

4

In [35]:
b.dtype

dtype('int32')

In [43]:
c=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype=np.float64)
c.size

12

In [45]:
c.itemsize

8

In [47]:
c.dtype

dtype('float64')

In [49]:
a[1]

3

In [55]:
b[1][1]

5

In [59]:
d=np.zeros(3)
d

array([0., 0., 0.])

In [63]:
e=np.zeros((3,3))
e

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
f=np.ones((3,3))
f

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [75]:
g=np.identity((3))
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
h=np.arange(10)
h

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
i=np.arange(5,10)
i

array([5, 6, 7, 8, 9])

In [83]:
j=np.arange(5,20,2)
j

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [87]:
k=np.linspace(1,10)
k

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [103]:
l=np.linspace(1,5,8)
l

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [109]:
m=np.arange(1,25)
m

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [111]:
m.reshape(3,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [117]:
n=m.reshape(8,3)
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [119]:
n.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [121]:
n.min()

1

In [123]:
n.max()

24

In [125]:
n.sum()

300

In [127]:
n.sum(axis=1)

array([ 6, 15, 24, 33, 42, 51, 60, 69])

In [129]:
n.sum(axis=0)

array([ 92, 100, 108])

In [131]:
np.sqrt(n)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069],
       [4.35889894, 4.47213595, 4.58257569],
       [4.69041576, 4.79583152, 4.89897949]])

In [135]:
np.std(n)

6.922186552431729

In [137]:
np.mean(n)

12.5

In [139]:
np.average(n)

12.5

In [141]:
np.median(n)

12.5

In [143]:
np.square(n)

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144],
       [169, 196, 225],
       [256, 289, 324],
       [361, 400, 441],
       [484, 529, 576]])

In [151]:
o=np.arange(1,5).reshape(2,2)
p=np.arange(6,10).reshape(2,2)
o

array([[1, 2],
       [3, 4]])

In [153]:
p

array([[6, 7],
       [8, 9]])

In [155]:
o+p

array([[ 7,  9],
       [11, 13]])

In [157]:
p-o

array([[5, 5],
       [5, 5]])

In [159]:
o*p

array([[ 6, 14],
       [24, 36]])

In [161]:
p/o

array([[6.        , 3.5       ],
       [2.66666667, 2.25      ]])

In [163]:
p%o

array([[0, 1],
       [2, 1]])

In [165]:
p**o

array([[   6,   49],
       [ 512, 6561]])

In [167]:
2*p

array([[12, 14],
       [16, 18]])

In [169]:
2-p

array([[-4, -5],
       [-6, -7]])

In [171]:
2/p

array([[0.33333333, 0.28571429],
       [0.25      , 0.22222222]])

In [173]:
o

array([[1, 2],
       [3, 4]])

In [175]:
p

array([[6, 7],
       [8, 9]])

In [177]:
o.dot(p)

array([[22, 25],
       [50, 57]])

In [179]:
q=np.arange(1,19)
q

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [181]:
q[0:2]

array([1, 2])

In [183]:
q[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [185]:
q[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [187]:
q[-1]

18

In [199]:
q[-5:-2]

array([14, 15, 16])

In [201]:
q[-5:]

array([14, 15, 16, 17, 18])

In [203]:
q[:-2]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [217]:
r=np.arange(1,17).reshape(4,4)
r

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [221]:
r[2,2]

11

In [223]:
r[2:,2]

array([11, 15])

In [225]:
r[2:,2:]

array([[11, 12],
       [15, 16]])

In [227]:
r[:2,:2]

array([[1, 2],
       [5, 6]])

In [229]:
r[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [231]:
r[1:2,1:2]

array([[6]])

In [235]:
r[-1:,0:2]

array([[13, 14]])

In [237]:
r

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [239]:
for row in r:
    print(row)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [243]:
for row in r:
    for col in row:
        print(col)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [249]:
for row in r.flat:
    print(row)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [251]:
s=np.arange(4).reshape(2,2)
s

array([[0, 1],
       [2, 3]])

In [253]:
t=np.arange(5,9).reshape(2,2)
t

array([[5, 6],
       [7, 8]])

In [257]:
np.vstack((s,t))

array([[0, 1],
       [2, 3],
       [5, 6],
       [7, 8]])

In [259]:
np.hstack((s,t))

array([[0, 1, 5, 6],
       [2, 3, 7, 8]])

In [267]:
u=np.arange(30).reshape(2,15);
u

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [275]:
np.vsplit(u,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [277]:
np.hsplit(u,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [279]:
v=np.arange(12).reshape(4,3)
v

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [281]:
v1=v>5
v1

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [283]:
v[v1]

array([ 6,  7,  8,  9, 10, 11])

In [287]:
v[v1]=-1
v

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [-1, -1, -1],
       [-1, -1, -1]])

In [299]:
for item in np.nditer(v):
    print(item)

0
1
2
3
4
5
-1
-1
-1
-1
-1
-1


In [303]:
for item in np.nditer(v,order='F'):
    print(item)

0
3
-1
-1
1
4
-1
-1
2
5
-1
-1


In [305]:
for item in np.nditer(v,order='F',flags=['external_loop']):
    print(item)

[ 0  3 -1 -1]
[ 1  4 -1 -1]
[ 2  5 -1 -1]
